use schemars::generate::SchemaSettings;
use schemars::transform::RecursiveTransform;
use schemars::{JsonSchema, Schema};
use serde::Serialize;
use serde_json::{Map, Value};

/// JSON Schema primitive types, as used in the `type` keyword.
#[derive(Serialize, Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "camelCase")]
pub enum InstanceType {
  Null,
  Boolean,
  Object,
  Array,
  Number,
  String,
  Integer,
}

impl InstanceType {
  pub fn as_str(&self) -> &'static str {
    match self {
      InstanceType::Null => "null",
      InstanceType::Boolean => "boolean",
      InstanceType::Object => "object",
      InstanceType::Array => "array",
      InstanceType::Number => "number",
      InstanceType::String => "string",
      InstanceType::Integer => "integer",
    }
  }

  pub fn parse(value: &str) -> Option<Self> {
    match value {
      "null" => Some(InstanceType::Null),
      "boolean" => Some(InstanceType::Boolean),
      "object" => Some(InstanceType::Object),
      "array" => Some(InstanceType::Array),
      "number" => Some(InstanceType::Number),
      "string" => Some(InstanceType::String),
      "integer" => Some(InstanceType::Integer),
      _ => None,
    }
  }

  /// Builds a schema of this type, with an optional `format`
  pub fn to_schema(self, format: Option<String>) -> Schema {
    let mut schema = Schema::default();
    schema.insert("type".to_owned(), self.as_str().into());
    if let Some(format) = format {
      schema.insert("format".to_owned(), format.into());
    }
    schema
  }

  /// Returns the instance types declared by the `type` keyword of a schema
  pub fn from_schema(schema: &Schema) -> Vec<Self> {
    match schema.get("type") {
      Some(Value::String(t)) => Self::parse(t).into_iter().collect(),
      Some(Value::Array(ts)) => ts.iter().filter_map(|t| t.as_str()).filter_map(Self::parse).collect(),
      _ => vec![],
    }
  }
}

/// Schema settings used to generate OpenAPI 3.0 compatible schemas.
pub fn schema_settings() -> SchemaSettings {
  SchemaSettings::openapi3()
    .with(|s| s.meta_schema = None)
    .with_transform(RecursiveTransform(nullable_reference))
}

/// Generates the schema of `T` without the definitions it depends on.
pub fn schema_for<T: ?Sized + JsonSchema>() -> Schema {
  schema_and_definitions_for::<T>().0
}

/// Generates the schema of `T` alongside the definitions (named schemas) it depends on.
///
/// Recursive references to `T` (`"$ref": "#"`) are replaced by a reference to the `T` component,
/// which is then added to the definitions.
pub fn schema_and_definitions_for<T: ?Sized + JsonSchema>() -> (Schema, Vec<(String, Schema)>) {
  let mut generator = schema_settings().into_generator();
  let mut schema = generator.root_schema_for::<T>();
  if let Some(obj) = schema.as_object_mut() {
    obj.remove("components");
  }
  let mut definitions: Vec<(String, Schema)> = generator
    .take_definitions(true)
    .into_iter()
    .filter_map(|(name, def)| Schema::try_from(def).ok().map(|def| (name, def)))
    .collect();

  let name = T::schema_name().to_string();
  let component_ref = format!("#/components/schemas/{name}");
  let mut is_recursive = schema
    .as_object_mut()
    .is_some_and(|obj| replace_root_reference_in_object(obj, &component_ref));
  for (_, def) in &mut definitions {
    is_recursive |= def
      .as_object_mut()
      .is_some_and(|obj| replace_root_reference_in_object(obj, &component_ref));
  }
  if is_recursive && !definitions.iter().any(|(def_name, _)| *def_name == name) {
    let mut def = schema.clone();
    def.remove("title");
    definitions.push((name, def));
  }

  (schema, definitions)
}

/// Replaces `"$ref": "#"` with `"$ref": <component_ref>`, returns `true` if a reference has been replaced.
fn replace_root_reference_in_object(obj: &mut Map<String, Value>, component_ref: &str) -> bool {
  let mut replaced = false;
  if obj.get("$ref").and_then(Value::as_str) == Some("#") {
    obj.insert("$ref".to_owned(), Value::String(component_ref.to_owned()));
    replaced = true;
  }
  for v in obj.values_mut() {
    replaced |= replace_root_reference(v, component_ref);
  }
  replaced
}

fn replace_root_reference(value: &mut Value, component_ref: &str) -> bool {
  match value {
    Value::Object(obj) => replace_root_reference_in_object(obj, component_ref),
    Value::Array(arr) => arr
      .iter_mut()
      .fold(false, |replaced, v| replace_root_reference(v, component_ref) | replaced),
    _ => false,
  }
}

/// Turns `{"anyOf": [<schema>, {"nullable": true, "enum": [null]}]}` (generated by schemars for an optional
/// reference) into `{"allOf": [<schema>], "nullable": true}`, which is better supported by OpenAPI 3.0 tooling.
fn nullable_reference(schema: &mut Schema) {
  let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) else {
    return;
  };
  let [first, second] = any_of.as_slice() else {
    return;
  };
  let inner = match (is_null_schema(first), is_null_schema(second)) {
    (false, true) => first.clone(),
    (true, false) => second.clone(),
    _ => return,
  };
  schema.remove("anyOf");
  schema.insert("allOf".to_owned(), Value::Array(vec![inner]));
  schema.insert("nullable".to_owned(), Value::Bool(true));
}

fn is_null_schema(value: &Value) -> bool {
  let Some(obj) = value.as_object() else {
    return false;
  };
  let null_enum = obj
    .get("enum")
    .and_then(Value::as_array)
    .is_some_and(|e| e.as_slice() == [Value::Null]);
  let null_const = obj.get("const") == Some(&Value::Null);
  (null_enum || null_const) && obj.keys().all(|k| matches!(k.as_str(), "nullable" | "enum" | "const"))
}

/// Sets a `title` on each `oneOf` subschema (when missing) so that enum variants can be told apart:
/// - variants with a single property are titled after this property
/// - variants with a single string enum value (either at the root or in a property) are titled after this value
#[doc(hidden)]
pub fn set_one_of_titles(schema: &mut Schema) {
  let Some(one_of) = schema.get_mut("oneOf").and_then(Value::as_array_mut) else {
    return;
  };
  for variant in one_of.iter_mut().filter_map(Value::as_object_mut) {
    let title = match variant.get("properties").and_then(Value::as_object) {
      Some(properties) => {
        let tag_value = properties
          .values()
          .find_map(|p| p.get("enum").and_then(Value::as_array))
          .and_then(|values| single_string_value(values));
        match tag_value {
          Some(tag_value) => Some(tag_value),
          None if properties.len() == 1 => properties.keys().next().cloned(),
          None => None,
        }
      }
      None => variant
        .get("enum")
        .and_then(Value::as_array)
        .and_then(|values| single_string_value(values)),
    };
    if let Some(title) = title {
      variant.entry("title").or_insert(Value::String(title));
    }
  }
}

fn single_string_value(values: &[Value]) -> Option<String> {
  match values {
    [Value::String(value)] => Some(value.clone()),
    _ => None,
  }
}
